Sys.setlocale(category = "LC_CTYPE", locale = "ko_KR.UTF-8")
rm(list=ls())
getwd()
setwd("../data/real_last")
if(!require(dplyr)) install.packages("dplyr"); library(dplyr)
if(!require(data.table)) install.packages("data.table"); library(data.table)
if(!require(clusterGeneration)) install.packages("clusterGeneration"); library(clusterGeneration)
if(!require(mnormt)) install.packages("mnormt"); library(mnormt)
if(!require(randomForest)) install.packages("randomForest"); library(randomForest)
if(!require(caret)) install.packages("caret"); library(caret)
# 데이터로드
train<-read.csv('train_chad.csv')
test<-read.csv('test_chad.csv')
label<-read.csv('train_label.csv')
colnames(train)

#전처리 위해 합친다
new <- rbind(train,test)
# acc_id 기준 wk에 들어있는 element를 세어준다 
#A1: acc_id 기준 활동주(activated_wk) 
#A2: acc_id 기준 활동주 동안의 접속일수 총합
A1 <-new %>% group_by(acc_id) %>% summarise(activated_wk = length(unique(wk)))
A2 <-new %>% group_by(acc_id) %>% summarise(cnt = sum(cnt_dt)) 
# 14만 행의 데이터셋
new_2 <- inner_join(A1,A2)
# A3: 접속일수 총합 / 활동주 = 주당평균접속일수
A3 <- new_2 %>% group_by(acc_id) %>% summarise(avg_day = round(cnt/activated_wk))
new_2 <- inner_join(new_2,A3)
colnames(new_2)



### acc_id 기준 설명변수별 총합 
### 추후 활동주(activated_wk)으로 나누어 주당평균 값들을 계산하기 위해
k1 <-new %>% group_by(acc_id) %>% summarise(wk_playtime = sum(play_time))
k2 <-new %>% group_by(acc_id) %>% summarise(wk_npcexp = sum(npc_exp))
k3 <-new %>% group_by(acc_id) %>% summarise(wk_npchongmun = sum(npc_hongmun))
k4 <-new %>% group_by(acc_id) %>% summarise(wk_questexp = sum(quest_exp))
k5 <-new %>% group_by(acc_id) %>% summarise(wk_questhongmun = sum(quest_hongmun))
k6 <-new %>% group_by(acc_id) %>% summarise(wk_itemhongmun = sum(item_hongmun))
k7 <-new %>% group_by(acc_id) %>% summarise(wk_gamecombattime = sum(game_combat_time))
k8 <-new %>% group_by(acc_id) %>% summarise(wk_getmoney = sum(get_money))
k9 <-new %>% group_by(acc_id) %>% summarise(wk_duelcnt = sum(duel_cnt))
k10 <-new %>% group_by(acc_id) %>% summarise(wk_duelwin = sum(duel_win))
k11 <-new %>% group_by(acc_id) %>% summarise(wk_partybattlecnt = sum(partybattle_cnt))
k12 <-new %>% group_by(acc_id) %>% summarise(wk_partybattlewin = sum(partybattle_win))
k13 <-new %>% group_by(acc_id) %>% summarise(wk_inzone_solo = sum(cnt_enter_inzone_solo))
k14 <-new %>% group_by(acc_id) %>% summarise(wk_inzone_light = sum(cnt_enter_inzone_light))
k15 <-new %>% group_by(acc_id) %>% summarise(wk_inzone_skilled = sum(cnt_enter_inzone_skilled))
k16 <-new %>% group_by(acc_id) %>% summarise(wk_inzone_normal = sum(cnt_enter_inzone_normal))
k17 <-new %>% group_by(acc_id) %>% summarise(wk_raid = sum(cnt_enter_raid))
k18 <-new %>% group_by(acc_id) %>% summarise(wk_raidlight = sum(cnt_enter_raid_light))
k19 <-new %>% group_by(acc_id) %>% summarise(wk_cnt_bam = sum(cnt_enter_bam))
k20 <-new %>% group_by(acc_id) %>% summarise(wk_cl_solo = sum(cnt_clear_inzone_solo))
k21 <-new %>% group_by(acc_id) %>% summarise(wk_cl_light = sum(cnt_clear_inzone_light))
k22 <-new %>% group_by(acc_id) %>% summarise(wk_cl_skilled = sum(cnt_clear_inzone_skilled))
k23 <-new %>% group_by(acc_id) %>% summarise(wk_cl_normal = sum(cnt_clear_inzone_normal))
k24 <-new %>% group_by(acc_id) %>% summarise(wk_cl_raid = sum(cnt_clear_raid))
k25 <-new %>% group_by(acc_id) %>% summarise(wk_cl_raidlight = sum(cnt_clear_raid_light))
k26 <-new %>% group_by(acc_id) %>% summarise(wk_cl_bam = sum(cnt_clear_bam))
k27 <-new %>% group_by(acc_id) %>% summarise(wk_nl_chat = sum(normal_chat))
k28 <-new %>% group_by(acc_id) %>% summarise(wk_wh_chat = sum(whisper_chat))
k29 <-new %>% group_by(acc_id) %>% summarise(wk_dis_chat = sum(district_chat))
k30 <-new %>% group_by(acc_id) %>% summarise(wk_party_chat = sum(party_chat))
k31 <-new %>% group_by(acc_id) %>% summarise(wk_guild_chat = sum(guild_chat))
k32 <-new %>% group_by(acc_id) %>% summarise(wk_fact_chat = sum(faction_chat))
k33 <-new %>% group_by(acc_id) %>% summarise(wk_buff = sum(cnt_use_buffitem))
k34 <-new %>% group_by(acc_id) %>% summarise(wk_gathering = sum(gathering_cnt))
k35 <-new %>% group_by(acc_id) %>% summarise(wk_making = sum(making_cnt))
k36 <-new %>% group_by(acc_id) %>% summarise(wk_party_time = sum(party_time))
k37 <-new %>% group_by(acc_id) %>% summarise(wk_member_count = sum(member_count))
k38 <-new %>% group_by(acc_id) %>% summarise(wk_give_money = sum(give_money))
k39 <-new %>% group_by(acc_id) %>% summarise(wk_give_grocery = sum(give_grocery))
k40 <-new %>% group_by(acc_id) %>% summarise(wk_rec_money = sum(rec_money))
k41 <-new %>% group_by(acc_id) %>% summarise(wk_rec_grocery = sum(rec_grocery))
# 새로 만든 파생변수의 변수명에 큰 의미는 없다.
# 파생변수에 대한 설명은 make_new.R 참고
k42 <-new %>% group_by(acc_id) %>% summarise(wk_X1 = sum(X1))
k43 <-new %>% group_by(acc_id) %>% summarise(wk_X2 = sum(X2))
k44 <-new %>% group_by(acc_id) %>% summarise(wk_X3 = sum(X3))
k45 <-new %>% group_by(acc_id) %>% summarise(wk_X4 = sum(X4))
k46 <-new %>% group_by(acc_id) %>% summarise(wk_X5 = sum(X5))
k47 <-new %>% group_by(acc_id) %>% summarise(wk_X6 = sum(X6))
k48 <-new %>% group_by(acc_id) %>% summarise(wk_X7 = sum(X7))
k49 <-new %>% group_by(acc_id) %>% summarise(wk_X8 = sum(X8))
k50 <-new %>% group_by(acc_id) %>% summarise(wk_X9 = sum(X9))
k51 <-new %>% group_by(acc_id) %>% summarise(wk_X10 = sum(X10))
k52 <-new %>% group_by(acc_id) %>% summarise(wk_X11 = sum(X11))
k53 <-new %>% group_by(acc_id) %>% summarise(wk_X12= sum(X12))
k54 <-new %>% group_by(acc_id) %>% summarise(wk_X13 = sum(X13))
k55 <-new %>% group_by(acc_id) %>% summarise(wk_X14 = sum(X14))
k56 <-new %>% group_by(acc_id) %>% summarise(wk_X15= sum(X15))
k57 <-new %>% group_by(acc_id) %>% summarise(wk_X16= sum(X16))
k58 <-new %>% group_by(acc_id) %>% summarise(wk_X17= sum(X17))
k59 <-new %>% group_by(acc_id) %>% summarise(wk_X18= sum(X18))
k60 <-new %>% group_by(acc_id) %>% summarise(wk_X19= sum(X19))
k61 <-new %>% group_by(acc_id) %>% summarise(wk_X20= sum(X20))
k62 <-new %>% group_by(acc_id) %>% summarise(wk_X21= sum(X21))
k63 <-new %>% group_by(acc_id) %>% summarise(wk_X22 = sum(X22))
k64 <-new %>% group_by(acc_id) %>% summarise(wk_X23 = sum(X23))
k65 <-new %>% group_by(acc_id) %>% summarise(wk_X24= sum(X24))
k66 <-new %>% group_by(acc_id) %>% summarise(wk_X25 = sum(X25))
k67 <-new %>% group_by(acc_id) %>% summarise(wk_X26= sum(X26))
k68 <-new %>% group_by(acc_id) %>% summarise(wk_X27 = sum(X27))
k69 <-new %>% group_by(acc_id) %>% summarise(wk_X28 = sum(X28))

# new_2에 inner_join : 14만 rows 형태의 데이터셋
new_2<-inner_join(new_2,k1)
new_2<-inner_join(new_2,k2)
new_2<-inner_join(new_2,k3)
new_2<-inner_join(new_2,k4)
new_2<-inner_join(new_2,k5)
new_2<-inner_join(new_2,k6)
new_2<-inner_join(new_2,k7)
new_2<-inner_join(new_2,k8)
new_2<-inner_join(new_2,k9)
new_2<-inner_join(new_2,k10)
new_2<-inner_join(new_2,k11)
new_2<-inner_join(new_2,k12)
new_2<-inner_join(new_2,k13)
new_2<-inner_join(new_2,k14)
new_2<-inner_join(new_2,k15)
new_2<-inner_join(new_2,k16)
new_2<-inner_join(new_2,k17)
new_2<-inner_join(new_2,k18)
new_2<-inner_join(new_2,k19)
new_2<-inner_join(new_2,k20)
new_2<-inner_join(new_2,k21)
new_2<-inner_join(new_2,k22)
new_2<-inner_join(new_2,k23)
new_2<-inner_join(new_2,k24)
new_2<-inner_join(new_2,k25)
new_2<-inner_join(new_2,k26)
new_2<-inner_join(new_2,k27)
new_2<-inner_join(new_2,k28)
new_2<-inner_join(new_2,k29)
new_2<-inner_join(new_2,k30)
new_2<-inner_join(new_2,k31)
new_2<-inner_join(new_2,k32)
new_2<-inner_join(new_2,k33)
new_2<-inner_join(new_2,k34)
new_2<-inner_join(new_2,k35)
new_2<-inner_join(new_2,k36)
new_2<-inner_join(new_2,k37)
new_2<-inner_join(new_2,k38)
new_2<-inner_join(new_2,k39)
new_2<-inner_join(new_2,k40)
new_2<-inner_join(new_2,k41)
new_2<-inner_join(new_2,k42)
new_2<-inner_join(new_2,k43)
new_2<-inner_join(new_2,k44)
new_2<-inner_join(new_2,k45)
new_2<-inner_join(new_2,k46)
new_2<-inner_join(new_2,k47)
new_2<-inner_join(new_2,k48)
new_2<-inner_join(new_2,k49)
new_2<-inner_join(new_2,k50)
new_2<-inner_join(new_2,k51)
new_2<-inner_join(new_2,k52)
new_2<-inner_join(new_2,k53)
new_2<-inner_join(new_2,k54)
new_2<-inner_join(new_2,k55)
new_2<-inner_join(new_2,k56)
new_2<-inner_join(new_2,k57)
new_2<-inner_join(new_2,k58)
new_2<-inner_join(new_2,k59)
new_2<-inner_join(new_2,k60)
new_2<-inner_join(new_2,k61)
new_2<-inner_join(new_2,k62)
new_2<-inner_join(new_2,k63)
new_2<-inner_join(new_2,k64)
new_2<-inner_join(new_2,k65)
new_2<-inner_join(new_2,k66)
new_2<-inner_join(new_2,k67)
new_2<-inner_join(new_2,k68)
new_2<-inner_join(new_2,k69)



##### 주당평균
B1 <- new_2 %>% group_by(acc_id) %>% summarise(avg_playtime = (wk_playtime/activated_wk))
B2 <- new_2 %>% group_by(acc_id) %>% summarise(avg_npc_exp = (wk_npcexp/activated_wk))
B3 <- new_2 %>% group_by(acc_id) %>% summarise(avg_npc_hongmun = (wk_npchongmun/activated_wk))
B4 <- new_2 %>% group_by(acc_id) %>% summarise(avg_quest_exp = (wk_questexp/activated_wk))
B5 <- new_2 %>% group_by(acc_id) %>% summarise(avg_quest_hongmun = (wk_questhongmun/activated_wk))
B6 <- new_2 %>% group_by(acc_id) %>% summarise(avg_item_hongmun = (wk_itemhongmun/activated_wk))
B7 <- new_2 %>% group_by(acc_id) %>% summarise(avg_combat_time = (wk_gamecombattime/activated_wk))
B8 <- new_2 %>% group_by(acc_id) %>% summarise(avg_get_money = (wk_getmoney/activated_wk))
B9 <- new_2 %>% group_by(acc_id) %>% summarise(avg_duel_cnt = (wk_duelcnt/activated_wk))
B10 <- new_2 %>% group_by(acc_id) %>% summarise(avg_duel_win = (wk_duelwin/activated_wk))
B11 <- new_2 %>% group_by(acc_id) %>% summarise(avg_party_battle_cnt = (wk_partybattlecnt/activated_wk))
B12 <- new_2 %>% group_by(acc_id) %>% summarise(avg_party_battle_win = (wk_partybattlewin/activated_wk))
B13 <- new_2 %>% group_by(acc_id) %>% summarise(avg_enter_solo = (wk_inzone_solo/activated_wk))
B14 <- new_2 %>% group_by(acc_id) %>% summarise(avg_enter_light = (wk_inzone_light/activated_wk))
B15 <- new_2 %>% group_by(acc_id) %>% summarise(avg_enter_skilled = (wk_inzone_skilled/activated_wk))
B16 <- new_2 %>% group_by(acc_id) %>% summarise(avg_enter_normal = (wk_inzone_normal/activated_wk))
B17 <- new_2 %>% group_by(acc_id) %>% summarise(avg_enter_raid = (wk_raid/activated_wk))
B18 <- new_2 %>% group_by(acc_id) %>% summarise(avg_enter_raidlight = (wk_raidlight/activated_wk))
B19 <- new_2 %>% group_by(acc_id) %>% summarise(avg_enter_bam = (wk_cnt_bam/activated_wk))
B20 <- new_2 %>% group_by(acc_id) %>% summarise(avg_cl_solo = (wk_cl_solo/activated_wk))
B21 <- new_2 %>% group_by(acc_id) %>% summarise(avg_cl_light = (wk_cl_light/activated_wk))
B22 <- new_2 %>% group_by(acc_id) %>% summarise(avg_cl_skilled = (wk_cl_skilled/activated_wk))
B23 <- new_2 %>% group_by(acc_id) %>% summarise(avg_cl_normal = (wk_cl_normal/activated_wk))
B24 <- new_2 %>% group_by(acc_id) %>% summarise(avg_cl_raid = (wk_cl_raid/activated_wk))
B25 <- new_2 %>% group_by(acc_id) %>% summarise(avg_cl_raidlight = (wk_cl_raidlight/activated_wk))
B26 <- new_2 %>% group_by(acc_id) %>% summarise(avg_cl_bam = (wk_cl_bam/activated_wk))
B27 <- new_2 %>% group_by(acc_id) %>% summarise(avg_normal_chat = (wk_nl_chat/activated_wk))
B28 <- new_2 %>% group_by(acc_id) %>% summarise(avg_whisper_chat = (wk_wh_chat/activated_wk))
B29 <- new_2 %>% group_by(acc_id) %>% summarise(avg_dis_chat = (wk_dis_chat/activated_wk))
B30 <- new_2 %>% group_by(acc_id) %>% summarise(avg_party_chat = (wk_party_chat/activated_wk))
B31 <- new_2 %>% group_by(acc_id) %>% summarise(avg_guild_chat = (wk_guild_chat/activated_wk))
B32 <- new_2 %>% group_by(acc_id) %>% summarise(avg_fact_chat = (wk_fact_chat/activated_wk))
B33 <- new_2 %>% group_by(acc_id) %>% summarise(avg_buff = (wk_buff/activated_wk))
B34 <- new_2 %>% group_by(acc_id) %>% summarise(avg_gathering = (wk_gathering/activated_wk))
B35 <- new_2 %>% group_by(acc_id) %>% summarise(avg_making = (wk_making/activated_wk))
B36 <- new_2 %>% group_by(acc_id) %>% summarise(avg_party_time = (wk_party_time/activated_wk))
B37 <- new_2 %>% group_by(acc_id) %>% summarise(avg_party_member = (wk_member_count/activated_wk))
B38 <- new_2 %>% group_by(acc_id) %>% summarise(avg_give_money = (wk_give_money/activated_wk))
B39 <- new_2 %>% group_by(acc_id) %>% summarise(avg_give_grocery = (wk_give_grocery/activated_wk))
B40 <- new_2 %>% group_by(acc_id) %>% summarise(avg_rec_money = (wk_rec_money/activated_wk))
B41 <- new_2 %>% group_by(acc_id) %>% summarise(avg_rec_grocery = (wk_rec_grocery/activated_wk))
B42 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X1 = (wk_X1/activated_wk))
B43 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X2 = (wk_X2/activated_wk))
B44 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X3 = (wk_X3/activated_wk))
B45 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X4 = (wk_X4/activated_wk))
B46 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X5 = (wk_X5/activated_wk))
B47 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X6 = (wk_X6/activated_wk))
B48 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X7 = (wk_X7/activated_wk))
B49 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X8 = (wk_X8/activated_wk))
B50 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X9 = (wk_X9/activated_wk))
B51 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X10 = (wk_X10/activated_wk))
B52 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X11 = (wk_X11/activated_wk))
B53 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X12 = (wk_X12/activated_wk))
B54 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X13 = (wk_X13/activated_wk))
B55 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X14 = (wk_X14/activated_wk))
B56 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X15 = (wk_X15/activated_wk))
B57 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X16 = (wk_X16/activated_wk))
B58 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X17 = (wk_X17/activated_wk))
B59 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X18 = (wk_X18/activated_wk))
B60 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X19 = (wk_X19/activated_wk))
B61 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X20 = (wk_X20/activated_wk))
B62 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X21 = (wk_X21/activated_wk))
B63 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X22 = (wk_X22/activated_wk))
B64 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X23 = (wk_X23/activated_wk))
B65 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X24 = (wk_X24/activated_wk))
B66 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X25 = (wk_X25/activated_wk))
B67 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X26 = (wk_X26/activated_wk))
B68 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X27 = (wk_X27/activated_wk))
B69 <- new_2 %>% group_by(acc_id) %>% summarise(avg_X28 = (wk_X28/activated_wk))

# 주당평균데이터로만 구성된 데이터셋
Week_activity <-inner_join(A1,A3)
Week_activity <- inner_join(Week_activity,B1)
Week_activity <- inner_join(Week_activity,B2)
Week_activity <- inner_join(Week_activity,B3)
Week_activity <- inner_join(Week_activity,B4)
Week_activity <- inner_join(Week_activity,B5)
Week_activity <- inner_join(Week_activity,B6)
Week_activity <- inner_join(Week_activity,B7)
Week_activity <- inner_join(Week_activity,B8)
Week_activity <- inner_join(Week_activity,B9)
Week_activity <- inner_join(Week_activity,B10)
Week_activity <- inner_join(Week_activity,B11)
Week_activity <- inner_join(Week_activity,B12)
Week_activity <- inner_join(Week_activity,B13)
Week_activity <- inner_join(Week_activity,B14)
Week_activity <- inner_join(Week_activity,B15)
Week_activity <- inner_join(Week_activity,B16)
Week_activity <- inner_join(Week_activity,B17)
Week_activity <- inner_join(Week_activity,B18)
Week_activity <- inner_join(Week_activity,B19)
Week_activity <- inner_join(Week_activity,B20)
Week_activity <- inner_join(Week_activity,B21)
Week_activity <- inner_join(Week_activity,B22)
Week_activity <- inner_join(Week_activity,B23)
Week_activity <- inner_join(Week_activity,B24)
Week_activity <- inner_join(Week_activity,B25)
Week_activity <- inner_join(Week_activity,B26)
Week_activity <- inner_join(Week_activity,B27)
Week_activity <- inner_join(Week_activity,B28)
Week_activity <- inner_join(Week_activity,B29)
Week_activity <- inner_join(Week_activity,B30)
Week_activity <- inner_join(Week_activity,B31)
Week_activity <- inner_join(Week_activity,B32)
Week_activity <- inner_join(Week_activity,B33)
Week_activity <- inner_join(Week_activity,B34)
Week_activity <- inner_join(Week_activity,B35)
Week_activity <- inner_join(Week_activity,B36)
Week_activity <- inner_join(Week_activity,B37)
Week_activity <- inner_join(Week_activity,B38)
Week_activity <- inner_join(Week_activity,B39)
Week_activity <- inner_join(Week_activity,B40)
Week_activity <- inner_join(Week_activity,B41)
Week_activity <- inner_join(Week_activity,B42)
Week_activity <- inner_join(Week_activity,B43)
Week_activity <- inner_join(Week_activity,B44)
Week_activity <- inner_join(Week_activity,B45)
Week_activity <- inner_join(Week_activity,B46)
Week_activity <- inner_join(Week_activity,B47)
Week_activity <- inner_join(Week_activity,B48)
Week_activity <- inner_join(Week_activity,B49)
Week_activity <- inner_join(Week_activity,B50)
Week_activity <- inner_join(Week_activity,B51)
Week_activity <- inner_join(Week_activity,B52)
Week_activity <- inner_join(Week_activity,B53)
Week_activity <- inner_join(Week_activity,B54)
Week_activity <- inner_join(Week_activity,B55)
Week_activity <- inner_join(Week_activity,B56)
Week_activity <- inner_join(Week_activity,B57)
Week_activity <- inner_join(Week_activity,B58)
Week_activity <- inner_join(Week_activity,B59)
Week_activity <- inner_join(Week_activity,B60)
Week_activity <- inner_join(Week_activity,B61)
Week_activity <- inner_join(Week_activity,B62)
Week_activity <- inner_join(Week_activity,B63)
Week_activity <- inner_join(Week_activity,B64)
Week_activity <- inner_join(Week_activity,B65)
Week_activity <- inner_join(Week_activity,B66)
Week_activity <- inner_join(Week_activity,B67)
Week_activity <- inner_join(Week_activity,B68)
Week_activity <- inner_join(Week_activity,B69)





################################################
################################################
test_id<-read.csv('test_id.csv')
Week_activity_train <-inner_join(label,Week_activity)
Week_activity_test<-inner_join(test_id,Week_activity)


write.csv(Week_activity_train,"../data/real_last/EDA_train2.csv",na="0",row.names = F)
write.csv(Week_activity_test,"../data/real_last/EDA_test2.csv",na="0",row.names = F)
